# Unterstütze die Entwicklung von aitema Open-Source-GovTech
# Möglichkeiten, das Projekt zu fördern:

# GitHub Sponsors (falls aktiviert)
# github: Aitema-gmbh

# Offener Aufruf für kommunale Förderprojekte
custom:
  - "https://aitema.de/loesungen/foerderung"
  - "https://aitema.de/kontakt"
