name: Terminvergabe CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aitema-gmbh/terminvergabe

jobs:
  backend:
    name: Backend (Node 20)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: terminvergabe_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Generate Prisma client
        working-directory: backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/terminvergabe_test
        run: npx prisma generate

      - name: Run Prisma migrations
        working-directory: backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/terminvergabe_test
        run: npx prisma migrate deploy

      - name: Run vitest
        working-directory: backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/terminvergabe_test
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-for-ci-only
        run: npm run test -- --reporter=verbose --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: backend/coverage/lcov.info
          flags: backend

  frontend-buerger:
    name: Frontend Buerger (SvelteKit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend-buerger/package-lock.json

      - name: Install dependencies
        working-directory: frontend-buerger
        run: npm ci

      - name: Run svelte-check
        working-directory: frontend-buerger
        run: npx svelte-check --tsconfig ./tsconfig.json
        continue-on-error: true

      - name: Build frontend-buerger
        working-directory: frontend-buerger
        run: npm run build

  frontend-mitarbeiter:
    name: Frontend Mitarbeiter (SvelteKit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend-mitarbeiter/package-lock.json

      - name: Install dependencies
        working-directory: frontend-mitarbeiter
        run: npm ci

      - name: Run svelte-check
        working-directory: frontend-mitarbeiter
        run: npx svelte-check --tsconfig ./tsconfig.json
        continue-on-error: true

      - name: Build frontend-mitarbeiter
        working-directory: frontend-mitarbeiter
        run: npm run build

  build-docker:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend-buerger
      - frontend-mitarbeiter
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    strategy:
      matrix:
        service:
          - name: backend
            context: backend
          - name: frontend-buerger
            context: frontend-buerger
          - name: frontend-mitarbeiter
            context: frontend-mitarbeiter

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service.name }}
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.service.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service.name }}

  deploy:
    name: Deploy to Hetzner
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    environment:
      name: production
      url: https://termin.aitema.de

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: 49.13.15.44
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e
            cd /opt/aitema/terminvergabe
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            git pull origin main
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            # Prisma Migrationen ausfuehren
            docker compose -f docker-compose.prod.yml exec -T backend npx prisma migrate deploy
            docker system prune -f
            echo "Deployment completed at $(date)"

      - name: Health check
        run: |
          sleep 30
          curl --fail --retry 5 --retry-delay 10 https://termin.aitema.de/api/health || echo "Health check warning"
